import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, Check, Globe2, MapPin, Clock3, PackageCheck, MessageCircle, Radar, ShieldCheck, Headphones } from 'lucide-react'
import Navbar from './Navbar'
import QuoteForm from './QuoteForm'
import ServicesCarousel from './ServicesCarousel'
import { industries, lanes, testimonials, ServiceItem } from '../data/content'

const hero='https://images.unsplash.com/photo-1606185540834-d6e7483ee1a4?auto=format&fit=crop&w=2200&q=85'
const port='https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1600&q=85'
const warehouse='https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1600&q=85'
const airplane='https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=85'
function Reveal({children,className=''}:{children:React.ReactNode,className?:string}){return <motion.div initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.6}} className={className}>{children}</motion.div>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
function SectionTitle({eyebrow,title,desc,dark=false}:{eyebrow:string,title:string,desc?:string,dark?:boolean}){return <div className="max-w-2xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className={`section-title ${dark?'text-white':'text-slate-950'}`}>{title}</h2>{desc&&<p className={`mt-5 text-lg leading-8 ${dark?'text-white/60':'text-slate-500'}`}>{desc}</p>}</div>}

export default function HomePage(){
  const [selectedService, setSelectedService] = useState<ServiceItem | null>(null)

  return <main className="overflow-hidden bg-white text-slate-950"><Navbar/>
<section id="home" className="relative min-h-[720px] bg-ink pt-32 lg:min-h-[760px]"><video autoPlay muted loop playsInline preload="auto" aria-label="Cargo operations" className="absolute inset-0 h-full w-full object-cover opacity-60"><source src="/ship.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,17,31,.94)_0%,rgba(7,17,31,.75)_50%,rgba(7,17,31,.35)_100%)]"/><div className="relative mx-auto max-w-content px-5 pb-20 pt-20 lg:px-8 lg:pt-28"><Reveal><Eyebrow>FREIGHT & LOGISTICS SERVICES</Eyebrow><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[.98] tracking-[-.045em] text-white sm:text-6xl lg:text-[74px]">Colombo Freight <span className="text-blue-400">moves cargo with care.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">End-to-end freight solutions connecting your cargo to markets around the world — with reliability, visibility and complete operational control.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#quote" className="btn-primary">Request a Quote <ArrowRight size={17}/></a><a href="#contact" className="btn-secondary">Contact Us</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-white/72">{['Freight Forwarding','Customs Brokerage','Island-wide Transport'].map(x=><span key={x} className="flex items-center gap-2"><Check size={15} className="text-teal"/>{x}</span>)}</div></Reveal></div></section>
<section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-content grid-cols-2 px-5 py-7 sm:grid-cols-3 lg:grid-cols-5 lg:px-8">{[['Colombo 02','Sri Lanka'],['011 230 4425','Phone'],['info@cmb-freight.com','Email'],['Suroor International','Trading affiliate'],['Paragon Cargo Solutions','Customs brokerage affiliate']].map(([a,b])=><div key={b} className="px-3 py-4 lg:border-r lg:last:border-r-0"><div className="text-xl font-bold tracking-tight">{a}</div><div className="mt-1 text-sm text-slate-500">{b}</div></div>)}</div></section>

{/* New Interactive Services Showcase Carousel */}
<ServicesCarousel onSelectService={(s) => setSelectedService(s)} />

<section id="quote" className="section bg-paper"><div className="mx-auto grid max-w-content gap-10 px-5 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-8"><Reveal><SectionTitle eyebrow="REQUEST A QUOTE" title="Plan your next shipment with Colombo Freight." desc="Share your origin, destination and cargo details. Our team will respond with the information you need."/></Reveal><Reveal><QuoteForm selectedService={selectedService} /></Reveal></div></section>
<section id="global-network" className="section bg-ink text-white"><div className="mx-auto grid max-w-content gap-14 px-5 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-8"><Reveal><SectionTitle dark eyebrow="COLOMBO FREIGHT" title="A Colombo-based freight and logistics partner." desc="Colombo Freight (Pvt) Ltd operates from Colombo 02, Sri Lanka, supporting cargo and logistics requirements."/><div className="mt-9 grid grid-cols-2 gap-4">{[['Freight','Forwarding'],['Customs','Brokerage'],['Cargo','Packaging'],['Transport','Island-wide']].map(([a,b])=><div key={b} className="border-l border-white/15 pl-4"><div className="text-2xl font-bold">{a}</div><div className="text-sm text-white/45">{b}</div></div>)}</div><a href="#contact" className="mt-8 inline-flex items-center gap-2 font-semibold text-blue-400">Contact Colombo Freight <ArrowRight size={17}/></a></Reveal><Reveal><div className="world-map relative min-h-[430px] overflow-hidden rounded-3xl border border-white/10 bg-white/[.035]"><div className="absolute inset-0 opacity-40 bg-[radial-gradient(circle_at_50%_45%,rgba(20,110,245,.30),transparent_50%)]"/>{[['Sri Lanka','61%','62%'],['Singapore','72%','60%'],['Dubai','55%','52%'],['India','63%','52%'],['China','75%','43%'],['Germany','47%','34%'],['UK','41%','30%'],['USA','18%','40%'],['Australia','82%','74%']].map(([n,l,t])=><div key={n} className="absolute" style={{left:l,top:t}}><span className="block h-2.5 w-2.5 rounded-full bg-teal shadow-[0_0_0_6px_rgba(41,182,166,.12)]"/><span className="mt-2 whitespace-nowrap text-[11px] text-white/55">{n}</span></div>)}<Globe2 className="absolute bottom-8 right-8 h-40 w-40 text-white/[.04]"/></div></Reveal></div></section>
<section id="solutions" className="section bg-white"><div className="mx-auto max-w-content px-5 lg:px-8"><Reveal><SectionTitle eyebrow="WHAT WE OFFER" title="Practical freight support for your cargo."/></Reveal><div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{[[Globe2,'Freight Forwarding','General freight forwarding services.'],[Radar,'Customs Brokerage','Brokerage support through Paragon Cargo Solutions.'],[ShieldCheck,'OOG Cargo','Handling for out-of-gauge cargo.'],[Headphones,'Warehousing & Transport','Warehousing facilities and island-wide transport services.']].map(([I,t,b]:any)=><Reveal key={t}><div><I className="text-brand"/><h3 className="mt-6 text-xl font-bold">{t}</h3><p className="mt-3 leading-7 text-slate-500">{b}</p></div></Reveal>)}</div></div></section>
<section id="tracking" className="section bg-paper"><div className="mx-auto grid max-w-content gap-14 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><Reveal><SectionTitle eyebrow="SMART LOGISTICS" title="Visibility from pickup to final delivery." desc="Track shipments, monitor milestones and keep your logistics operations connected from a single experience."/><ul className="mt-7 space-y-3 text-slate-600">{['Real-time shipment tracking','Milestone notifications','Shipping documents','Estimated arrival updates','Centralized shipment history'].map(x=><li key={x} className="flex items-center gap-3"><Check size={18} className="text-teal"/>{x}</li>)}</ul><a href="#" className="mt-8 inline-flex items-center gap-2 font-semibold text-brand">Track a Shipment <ArrowRight size={17}/></a></Reveal><Reveal><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-soft sm:p-8"><p className="text-xs font-bold tracking-widest text-slate-400">COLOMBO OFFICE</p><h3 className="mt-1 text-2xl font-bold">Colombo Freight (Pvt) Ltd</h3><div className="mt-8 flex items-center gap-4 border-y border-slate-100 py-6"><MapPin className="text-brand"/><div><div className="font-bold">29/11 Chapel Lane</div><div className="text-sm text-slate-400">Colombo 02, Sri Lanka</div></div></div><div className="mt-7 space-y-5">{[['Phone','011 230 4425'],['Email','info@cmb-freight.com'],['Trading affiliate','Suroor International'],['Customs brokerage','Paragon Cargo Solutions']].map(([l,v],i)=><div key={l} className="flex items-center gap-4"><div className="grid h-8 w-8 place-items-center rounded-full bg-brand text-white">{i+1}</div><div><div className="font-semibold">{l}</div><div className="text-sm text-slate-400">{v}</div></div></div>)}</div><a href="mailto:info@cmb-freight.com" className="mt-8 flex items-center justify-between rounded-xl bg-slate-50 p-4 text-brand"><span className="flex items-center gap-2 text-sm font-semibold"><Clock3 size={16}/> Email Colombo Freight</span><strong>→</strong></a></div></Reveal></div></section>
<section className="section bg-white"><div className="mx-auto max-w-content px-5 lg:px-8"><Reveal><SectionTitle eyebrow="HOW IT WORKS" title="Shipping made simple."/></Reveal><div className="mt-12 grid gap-5 md:grid-cols-4">{[['01','Request a Quote','Submit your route and shipment details.'],['02','Plan Your Shipment','We arrange the optimal transport solution.'],['03','Track Your Cargo','Follow every major shipment milestone.'],['04','Delivered','Cargo reaches its destination safely and efficiently.']].map(([n,t,b])=><Reveal key={n}><div className="relative border-t border-slate-200 pt-6"><span className="text-sm font-black text-brand">{n}</span><h3 className="mt-5 text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{b}</p></div></Reveal>)}</div></div></section>
<section id="industries" className="section bg-paper"><div className="mx-auto max-w-content px-5 lg:px-8"><Reveal><SectionTitle eyebrow="INDUSTRIES" title="Logistics expertise for every industry."/></Reveal><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{industries.map((x,i)=><Reveal key={x}><div className="group relative min-h-48 overflow-hidden rounded-2xl bg-ink p-6 text-white"><img loading="lazy" src={[port,warehouse,airplane,hero][i%4]} alt="" className="absolute inset-0 h-full w-full object-cover opacity-35 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/35 to-transparent"/><div className="relative flex h-full items-end"><h3 className="text-lg font-bold">{x}</h3></div></div></Reveal>)}</div></div></section>
<section className="section bg-white"><div className="mx-auto max-w-content px-5 lg:px-8"><Reveal><SectionTitle eyebrow="POPULAR TRADE LANES" title="Routes that keep business moving."/></Reveal><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{lanes.map(([a,b,m])=><Reveal key={a+b}><div className="rounded-2xl border border-slate-200 p-6"><div className="flex items-center justify-between text-xs font-bold text-slate-400"><span>{m} FREIGHT</span><PackageCheck size={18}/></div><div className="mt-7 flex items-center gap-3 text-lg font-bold"><span>{a}</span><ArrowRight size={17} className="text-brand"/><span>{b}</span></div><div className="mt-5 flex justify-between border-t border-slate-100 pt-5 text-sm"><span className="text-slate-400">Transit estimate on request</span><a href="#quote" className="font-semibold text-brand">Request Rate</a></div></div></Reveal>)}</div></div></section>
<section id="about-us" className="section bg-paper"><div className="mx-auto grid max-w-content gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><Reveal><div className="overflow-hidden rounded-3xl"><img loading="lazy" src={port} alt="Global logistics port operation" className="min-h-[460px] w-full object-cover"/></div></Reveal><Reveal><SectionTitle eyebrow="ABOUT US" title="Colombo Freight (Pvt) Ltd." desc="An active freight and logistics company operating in Colombo, Sri Lanka."/><div className="mt-8 grid grid-cols-2 gap-6">{[['Colombo 02','Sri Lanka'],['02','Affiliated companies'],['Suroor International','Trading company'],['Paragon Cargo Solutions','Customs brokerage']].map(([a,b])=><div key={b}><strong className="text-2xl">{a}</strong><div className="text-sm text-slate-400">{b}</div></div>)}</div><a href="#contact" className="mt-8 inline-flex items-center gap-2 font-semibold text-brand">Contact Colombo Freight <ArrowRight size={17}/></a></Reveal></div></section>
<section id="contact" className="section bg-white"><div className="mx-auto max-w-content px-5 lg:px-8"><Reveal><SectionTitle eyebrow="CONTACT" title="Contact Colombo Freight."/></Reveal><div className="mt-12 grid gap-4 lg:grid-cols-3">{testimonials.map(t=><Reveal key={t.name}><blockquote className="h-full rounded-2xl border border-slate-200 p-7"><p className="text-lg leading-8 text-slate-700">“{t.quote}”</p><footer className="mt-8 border-t border-slate-100 pt-5"><strong>{t.name}</strong><div className="mt-1 text-sm text-slate-400">{t.role} • {t.company} • {t.country}</div></footer></blockquote></Reveal>)}</div></div></section>
<section className="bg-ink px-5 py-20 text-white lg:px-8"><Reveal className="mx-auto max-w-content rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_85%_20%,rgba(20,110,245,.28),transparent_32%)] p-8 sm:p-12 lg:p-16"><Eyebrow>CONTACT COLOMBO FREIGHT</Eyebrow><h2 className="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">Discuss your cargo requirements.</h2><p className="mt-5 max-w-2xl text-lg text-white/60">Our Colombo office can assist with freight forwarding, customs brokerage, cargo handling and transport services.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#quote" className="btn-primary">Request a Quote <ArrowRight size={17}/></a><a href="tel:+94112304425" className="btn-secondary">Call 011 230 4425</a></div></Reveal></section>
<footer className="bg-[#050c16] px-5 pb-8 pt-16 text-white lg:px-8"><div className="mx-auto grid max-w-content gap-10 md:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><a href="#" className="inline-block"><img src="/logos/logo-white.svg" alt="Colombo Freight" className="h-10 w-auto max-w-[200px] object-contain" /></a><p className="mt-4 max-w-sm leading-7 text-white/45">Freight forwarding and logistics services from Colombo, Sri Lanka.</p><p className="mt-4 text-sm text-white/45">29/11 Chapel Lane, Colombo 02, Sri Lanka<br/><a href="mailto:info@cmb-freight.com">info@cmb-freight.com</a><br/><a href="tel:+94112304425">011 230 4425</a></p></div>{[['Services',['Ocean Freight','Air Freight','Road Freight','Warehousing','Customs Clearance']],['Company',['About','Global Network','Careers','News','Contact']],['Support',['Track Shipment','Request Quote','FAQs','Customer Support']]].map(([h,items]:any)=><div key={h}><h3 className="text-sm font-bold">{h}</h3><ul className="mt-4 space-y-3 text-sm text-white/45">{items.map((x:string)=><li key={x}><a href="#" className="hover:text-white">{x}</a></li>)}</ul></div>)}</div><div className="mx-auto mt-14 flex max-w-content flex-col gap-4 border-t border-white/10 pt-6 text-sm text-white/35 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Colombo Freight (Pvt) Ltd</span><div className="flex gap-5"><a href="#">Privacy Policy</a><a href="#">Terms & Conditions</a><a href="#">Cookie Policy</a></div></div></footer><a aria-label="Contact us" href="#" className="fixed bottom-5 right-5 z-40 grid h-12 w-12 place-items-center rounded-full bg-teal text-white shadow-xl transition hover:scale-105"><MessageCircle size={21}/></a></main>}
